### PR TITLE
Update dalle_back.ipynb

### PR DESCRIPTION
**Pull request by CodeAunt**
The new version deepspeed is not compatible. The code can run under this version limit.

### CODE REVIEW

**Comment by rom1504** [comment]
what do you mean deepspeed is not compatible exactly ?

**Comment by CodeAunt** [comment]
> what do you mean deepspeed is not compatible exactly ?

The current code in repository is compatible with earlier versions of deepspeed.

**Comment by rom1504** [comment]
I still don't understand what you mean.
Dalle pytorch is definitely compatible with deepspeed

**Comment by jabowery** [comment]
Perhaps she meant this:

image

**Comment by CodeAunt** [comment]
> Perhaps she meant this:
> 
> image
yes, latest deepspeed is not compatible, the proposed method aims to fix this

**Pull request closed without merging**
